apiVersion: apps/v1
kind: Deployment
metadata:
  name: lms-app
  namespace: lms-backend
  labels:
    app: lms-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lms-app
  template:
    metadata:
      labels:
        app: lms-app
    spec:
      containers:
      - name: lms-app
        image: 1blacklung1/lms-marketplace:latest
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 8080
        env:
          - name: ConnectionStrings__DefaultConnection
            valueFrom:
              secretKeyRef:
                name: secret
                key: connection-string
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 60
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1