apiVersion: v1
kind: Service
metadata:
  name: lms-app-service
  namespace: lms-backend
spec:
  type: NodePort
  selector:
    app: lms-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080