apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: db
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/postgres"
  persistentVolumeReclaimPolicy: Retain